from pathlib import Path
import html
import re

ROOT = Path(__file__).resolve().parents[1]
CHAPTER = ROOT / "docs/chapters/complete/Chapter178_AtypicalAndSerotonergicAntidepressants.html"


def extract_figures(source: str) -> dict[int, dict[str, str]]:
    pat = re.compile(
        r'<figure class="source-figure[^"]*reference-image[^"]*"[^>]*>\s*'
        r'<img[^>]+src="(data:image/[^"]+)"[^>]*alt="([^"]*)"[^>]*>\s*'
        r"<figcaption[^>]*>(.*?)</figcaption>",
        re.S,
    )
    figures = {}
    for index, match in enumerate(pat.finditer(source), 1):
        figures[index] = {
            "src": match.group(1),
            "alt": html.unescape(match.group(2)),
            "cap": html.unescape(re.sub("<.*?>", "", match.group(3))).strip(),
        }
    return figures


def source_card(figures: dict[int, dict[str, str]], idx: int, title: str, note: str) -> str:
    fig = figures[idx]
    return f"""
    <article class="source-card">
      <div class="source-card__label">Tintinalli source</div>
      <h3 class="source-card__title">{html.escape(title)}</h3>
      <p>{html.escape(note)}</p>
      <figure class="reference-image">
        <img src="{fig['src']}" alt="{html.escape(fig['alt'])}" loading="lazy" decoding="async">
        <figcaption>{html.escape(fig['cap'])}</figcaption>
      </figure>
    </article>
    """


def rosen_card(title: str, note: str, delta: str) -> str:
    return f"""
    <article class="source-card rosen-source">
      <div class="source-card__label">Rosen source check</div>
      <h3 class="source-card__title">{html.escape(title)}</h3>
      <p>{html.escape(note)}</p>
      <div class="source-delta"><strong><u>Rosen vs Tintinalli:</u></strong> {html.escape(delta)}</div>
    </article>
    """


def mcq(number: int, answer: str, stem: str, options: list[tuple[str, str]], rationales: dict[str, str]) -> str:
    buttons = "\n".join(
        f'<button class="mcq-opt" type="button" data-option-key="{key}">{key}. {html.escape(text)}</button>'
        for key, text in options
    )
    explains = "\n".join(
        f'<div class="opt-explain {"is-correct" if key == answer else "is-wrong"}" hidden>'
        f"<strong>{key}. {html.escape(text)}</strong><span>{html.escape(rationales[key])}</span></div>"
        for key, text in options
    )
    return f"""
    <article class="mcq-wrapper" data-answer="{answer}" data-answered="false">
      <p class="mcq-stem">Q{number}. {html.escape(stem)}</p>
      <div class="mcq-options">{buttons}</div>
      <div class="mcq-result" hidden></div>
      <div class="mcq-explains">{explains}</div>
    </article>
    """


def build_mcqs() -> str:
    raw = [
        ("B", "A patient has a generalized seizure several hours after a large antidepressant ingestion and the ECG shows sinus tachycardia with QRS widening. Which exposure is most concerning?", [("A", "Sertraline only"), ("B", "Bupropion extended release"), ("C", "Mirtazapine only"), ("D", "Trazodone only")], {"A": "Isolated SSRI overdose is usually milder and less seizure-prone than bupropion.", "B": "Bupropion, especially extended-release, is strongly associated with delayed seizures and QRS/QT issues.", "C": "Mirtazapine is usually sedating and less likely to cause severe seizures.", "D": "Trazodone can cause hypotension/QT effects, but delayed seizures point more strongly to bupropion."}),
        ("A", "Best initial ED approach for bupropion overdose with recurrent seizures?", [("A", "Airway readiness, benzodiazepines, ECG monitoring, electrolytes, and toxicology/ICU involvement"), ("B", "Flumazenil"), ("C", "Naloxone alone"), ("D", "Immediate discharge after one normal ECG")], {"A": "Bupropion seizures can recur and deteriorate; supportive resuscitation and monitoring drive care.", "B": "Flumazenil can provoke seizures.", "C": "Naloxone does not treat bupropion toxicity.", "D": "Delayed seizures make early discharge unsafe."}),
        ("D", "Which trazodone toxicity pattern is board-relevant?", [("A", "Pure cholinergic crisis"), ("B", "Methemoglobinemia"), ("C", "Opioid toxidrome"), ("D", "CNS depression, hypotension, and QT prolongation")], {"A": "Not the typical trazodone pattern.", "B": "Not typical.", "C": "Not typical unless coingestion exists.", "D": "Trazodone overdose commonly centers on sedation, alpha blockade hypotension, and QT effects."}),
        ("C", "A trazodone overdose patient has persistent hypotension after fluids. Next best escalation?", [("A", "Long-acting oral antihypertensive"), ("B", "Physostigmine"), ("C", "Direct-acting vasopressor such as norepinephrine"), ("D", "Forced diuresis")], {"A": "This worsens hypotension.", "B": "Not indicated for trazodone shock.", "C": "Alpha blockade can require direct vasopressors.", "D": "Forced diuresis does not clear trazodone."}),
        ("A", "Most isolated SSRI overdoses are managed with:", [("A", "Supportive care and observation with ECG/serotonin-syndrome screening when indicated"), ("B", "Routine hemodialysis"), ("C", "Empiric sodium thiosulfate"), ("D", "Charcoal at 24 hours for everyone")], {"A": "Most SSRI ingestions are benign; screen for citalopram/escitalopram ECG risk and serotonin syndrome.", "B": "SSRIs are not managed by routine dialysis.", "C": "Cyanide antidote is unrelated.", "D": "Charcoal is time/airway dependent, not universal."}),
        ("B", "Which SSRI exposure deserves particular ECG attention?", [("A", "Fluoxetine at a therapeutic dose"), ("B", "Citalopram or escitalopram overdose"), ("C", "Mirtazapine monotherapy"), ("D", "Bupropion missed dose")], {"A": "Therapeutic fluoxetine is not the ECG overdose trap.", "B": "Citalopram/escitalopram overdoses are associated with QT prolongation and torsades risk.", "C": "Not an SSRI and usually less ECG-toxic.", "D": "Missed dose is not overdose."}),
        ("D", "An SNRI overdose with severe hypertension, tachycardia, and seizures most strongly suggests:", [("A", "Mild mirtazapine ingestion"), ("B", "Isolated trazodone sleepiness"), ("C", "Ibuprofen toxicity"), ("D", "Venlafaxine/desvenlafaxine toxicity")], {"A": "Mirtazapine is usually milder/sedating.", "B": "Trazodone is more hypotension/QT.", "C": "NSAID toxicity does not fit.", "D": "Venlafaxine can cause sympathomimetic features, seizures, and cardiovascular toxicity."}),
        ("C", "Serotonin syndrome is most suggested by:", [("A", "Lead-pipe rigidity and bradyreflexia over days"), ("B", "Pinpoint pupils and apnea"), ("C", "Clonus, hyperreflexia, agitation, diaphoresis, and hyperthermia after serotonergic exposure"), ("D", "Isolated orthostatic hypotension")], {"A": "This favors NMS.", "B": "This favors opioid toxicity.", "C": "Clonus and hyperreflexia are key serotonin syndrome findings.", "D": "Not enough for serotonin syndrome."}),
        ("A", "First-line medication for agitation and tremor in serotonin syndrome is:", [("A", "Benzodiazepines"), ("B", "Haloperidol escalation"), ("C", "Flumazenil"), ("D", "Beta blocker monotherapy")], {"A": "Benzodiazepines reduce agitation and muscle activity.", "B": "Dopamine antagonists can complicate hyperthermic toxidromes.", "C": "Can provoke seizures.", "D": "Does not treat the core syndrome and can be risky."}),
        ("B", "Severe serotonin syndrome with temperature 41 C and rigidity requires:", [("A", "Acetaminophen only"), ("B", "Aggressive sedation, active cooling, paralysis/intubation when needed, and ICU care"), ("C", "Observation at home"), ("D", "Physostigmine")], {"A": "Antipyretics do not stop muscle heat generation.", "B": "Severe cases need rapid control of muscle activity and temperature.", "C": "Unsafe.", "D": "Not appropriate."}),
        ("D", "Cyproheptadine is best described as:", [("A", "An IV paralytic"), ("B", "A dialysis enhancer"), ("C", "A charcoal substitute"), ("D", "An oral/enteral serotonin antagonist adjunct for moderate/severe serotonin syndrome")], {"A": "It is not a paralytic.", "B": "It does not enhance dialysis.", "C": "It is not decontamination.", "D": "Cyproheptadine can be used as enteral adjunct after supportive care."}),
        ("A", "Which distinction favors serotonin syndrome over NMS?", [("A", "Rapid onset with clonus and hyperreflexia"), ("B", "Slow onset over days with lead-pipe rigidity"), ("C", "Dopamine antagonist withdrawal only"), ("D", "Normal neuromuscular exam")], {"A": "This is the classic serotonin syndrome pattern.", "B": "Favors NMS.", "C": "Not serotonin syndrome.", "D": "Does not support diagnosis."}),
        ("C", "Drug Dose Reference should be used for:", [("A", "Replacing treatment sections"), ("B", "Parking all treatment tables away from topics"), ("C", "Quick recap after full treatment discussion"), ("D", "Hiding the clinical algorithm")], {"A": "Treatment must be discussed in each topic.", "B": "Tables belong next to topic.", "C": "Correct: it is only a quick dose recap.", "D": "Wrong use."}),
        ("B", "Why are extended-release bupropion ingestions observed longer?", [("A", "They cause immediate cyanide release"), ("B", "Delayed absorption and delayed/recurrent seizures"), ("C", "They are removed by naloxone"), ("D", "They never cause symptoms")], {"A": "No cyanide.", "B": "Delayed seizures are the core risk.", "C": "Naloxone does not reverse bupropion.", "D": "False."}),
        ("D", "A patient taking linezolid plus an SSRI develops clonus and fever. Mechanism?", [("A", "Opioid agonism"), ("B", "Anticholinergic blockade only"), ("C", "Lithium redistribution"), ("D", "Serotonergic excess from interacting agents")], {"A": "Not opioid.", "B": "Does not explain clonus.", "C": "Not lithium.", "D": "Linezolid has MAOI activity and can contribute to serotonin syndrome."}),
        ("A", "Which finding requires telemetry after antidepressant overdose?", [("A", "QT prolongation or QRS widening"), ("B", "Normal vitals and normal ECG after adequate observation"), ("C", "Remote tiny ingestion with no symptoms"), ("D", "Mild nausea only")], {"A": "ECG interval abnormalities drive monitored care.", "B": "May support discharge depending scenario.", "C": "Lower risk.", "D": "Not enough alone."}),
        ("C", "Which seizure drug strategy is preferred in these toxicologic seizures?", [("A", "Phenytoin first for all"), ("B", "No treatment"), ("C", "Benzodiazepines first"), ("D", "More antidepressant")], {"A": "Phenytoin is not first-line for most toxicologic seizures.", "B": "Unsafe.", "C": "Correct.", "D": "Wrong."}),
        ("B", "Which patient should not be cleared early?", [("A", "Asymptomatic SSRI ingestion with normal ECG after adequate observation"), ("B", "Large extended-release bupropion ingestion still within delayed seizure window"), ("C", "Tiny accidental mirtazapine ingestion with normal observation"), ("D", "Remote trazodone ingestion with normal vitals and ECG")], {"A": "May be reasonable if criteria met.", "B": "Delayed seizures make early clearance unsafe.", "C": "Likely lower risk.", "D": "May be lower risk after adequate observation."}),
        ("D", "What makes SNRI overdose different from most SSRI overdose?", [("A", "No seizure risk ever"), ("B", "Always requires dialysis"), ("C", "Always produces opioid toxidrome"), ("D", "More sympathomimetic/cardiovascular and seizure risk, especially venlafaxine")], {"A": "False.", "B": "No.", "C": "No.", "D": "Correct."}),
        ("A", "Most important bedside endpoint in severe serotonin syndrome treatment is:", [("A", "Stopping muscle activity and lowering core temperature"), ("B", "Lowering fever with acetaminophen alone"), ("C", "Waiting for a serum serotonin level"), ("D", "Forcing urine output")], {"A": "Hyperthermia is generated by muscle activity.", "B": "Not enough.", "C": "No useful ED serum serotonin test.", "D": "Not the main issue."}),
        ("C", "Which medication combination is high risk for serotonin syndrome?", [("A", "Acetaminophen plus ibuprofen"), ("B", "Insulin plus dextrose"), ("C", "SSRI plus MAOI/linezolid/tramadol or multiple serotonergic agents"), ("D", "Albuterol plus ipratropium")], {"A": "No.", "B": "No.", "C": "Correct interaction pattern.", "D": "No."}),
        ("B", "For trazodone-related torsades, treat with:", [("A", "Calcium carbonate orally"), ("B", "Magnesium sulfate and correction of electrolytes"), ("C", "Naloxone"), ("D", "Fomepizole")], {"A": "Not torsades care.", "B": "Magnesium is first-line for torsades.", "C": "Not opioid.", "D": "Toxic alcohol antidote."}),
        ("A", "Which symptom cluster after SSRI overdose should trigger serotonin syndrome treatment rather than simple observation?", [("A", "Clonus, agitation, diaphoresis, hyperthermia"), ("B", "Mild nausea only"), ("C", "Sleepiness with normal vitals only"), ("D", "Normal neuromuscular exam")], {"A": "This is serotonin toxicity.", "B": "Usually supportive observation.", "C": "Not enough.", "D": "Not serotonin syndrome."}),
        ("D", "Which statement about mirtazapine overdose is most accurate?", [("A", "It always causes fatal dysrhythmia"), ("B", "It causes cyanide poisoning"), ("C", "It always needs hemodialysis"), ("D", "It is often sedating and supportive-care managed, but coingestions still matter")], {"A": "False.", "B": "No.", "C": "No.", "D": "Correct."}),
        ("C", "Disposition after atypical/serotonergic antidepressant ingestion should consider:", [("A", "Only the drug name"), ("B", "Only one normal blood pressure"), ("C", "Formulation, time since ingestion, ECG, seizures, serotonin findings, coingestants, and symptom trend"), ("D", "Urine drug screen alone")], {"A": "Too narrow.", "B": "Insufficient.", "C": "Correct integrated disposition.", "D": "UDS is not enough."}),
        ("A", "Best overall ED summary for this chapter?", [("A", "Risk-stratify by agent, formulation, ECG, seizure risk, and serotonin toxicity; treat supportively with targeted escalation"), ("B", "All antidepressant overdoses are benign"), ("C", "All need dialysis"), ("D", "All are treated with flumazenil")], {"A": "Correct chapter-level approach.", "B": "Bupropion, venlafaxine, citalopram, trazodone, and serotonin syndrome can be dangerous.", "C": "Wrong.", "D": "Dangerous and wrong."}),
    ]
    return "\n".join(mcq(i, *item) for i, item in enumerate(raw, 1))


STYLE = r"""
:root{--header-h:56px;--sidebar-w:280px;--bg:#f7f3ec;--paper:#fffdf8;--ink:#162033;--muted:#5f6b7a;--line:#d8cfc2;--teal:#0f766e;--indigo:#4338ca;--red:#be123c;--gold:#b45309;--soft:#eef8f5;--warn:#fff7df;--danger:#fff1f2;--shadow:0 14px 34px rgba(16,24,40,.12)}
html[data-theme=dark]{--bg:#111827;--paper:#172033;--ink:#f8fafc;--muted:#cbd5e1;--line:#334155;--soft:#12342f;--warn:#342c13;--danger:#351b2a;--shadow:0 18px 44px rgba(0,0,0,.35)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.65 "Segoe UI",Arial,sans-serif;letter-spacing:0}
#top-header{position:fixed;inset:0 0 auto 0;height:var(--header-h);z-index:50;display:flex;align-items:center;gap:10px;padding:0 16px;background:linear-gradient(90deg,#0f766e,#4338ca);color:#fff;box-shadow:0 2px 12px rgba(0,0,0,.22)}.hdr-btn{border:0;border-radius:7px;background:rgba(255,255,255,.18);color:#fff;min-width:36px;height:36px;padding:0 10px;cursor:pointer;font:inherit;display:inline-flex;align-items:center;justify-content:center}.hdr-title{font-weight:850}.theme-btn{margin-left:auto}
.app{min-height:100vh}#sidebar.sidebar{position:fixed;top:var(--header-h);left:0;bottom:0;width:var(--sidebar-w);overflow:auto;padding:14px;background:rgba(255,253,248,.97);border-right:1px solid var(--line);z-index:40;box-shadow:8px 0 24px rgba(0,0,0,.08)}html[data-theme=dark] #sidebar.sidebar{background:rgba(23,32,51,.97)}.sidebar-close{float:right}.sidebar__block{clear:both;margin:16px 0}.sidebar__kicker{color:var(--muted);font-size:12px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.sidebar h2{margin:6px 0;color:var(--teal);font-size:18px;line-height:1.25}.meta{margin:4px 0;color:var(--muted);font-size:12px;line-height:1.4}.sidebar__link{display:block;margin:3px 0;padding:7px 8px;border-left:3px solid transparent;border-radius:0 7px 7px 0;color:var(--ink);text-decoration:none;font-size:14px}.sidebar__link:hover,.sidebar__link.is-active{border-left-color:var(--indigo);background:var(--danger);color:var(--indigo)}
#main.main{margin-left:var(--sidebar-w);padding:calc(var(--header-h) + 24px) 22px 48px}.content-wrap{max-width:1120px;margin:0 auto}.utility-bar{display:flex;gap:8px;align-items:center;margin-bottom:14px;color:var(--muted);font-size:13px}.hero,.section,.question-set{background:var(--paper);border:1px solid var(--line);border-radius:8px;box-shadow:var(--shadow)}.hero{padding:24px;border-top:5px solid var(--teal)}.eyebrow{color:var(--indigo);font-size:12px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.hero__title{margin:6px 0 8px;color:var(--teal);font-size:34px;line-height:1.12;letter-spacing:0}.lede{font-size:18px;max-width:74ch}.section,.question-set{margin-top:18px;padding:22px;scroll-margin-top:72px}h2{margin:0 0 12px;padding-bottom:8px;border-bottom:2px solid color-mix(in srgb,var(--teal),transparent 55%);color:#0f4f4a;font-size:24px}h3{margin:18px 0 8px;color:var(--indigo);font-size:18px}p{margin:10px 0}mark{background:#fff2a8;color:#111827;border-radius:4px;padding:1px 5px}u{text-decoration-color:var(--red);text-decoration-thickness:2px;text-underline-offset:3px}strong{font-weight:850;color:var(--indigo)}
.callout{margin:14px 0;padding:13px 15px;border-left:5px solid var(--teal);background:var(--soft);border-radius:7px}.callout.warn{border-left-color:var(--gold);background:var(--warn)}.callout.danger{border-left-color:var(--red);background:var(--danger)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.mini-card{border:1px solid var(--line);border-radius:8px;padding:13px;background:rgba(255,255,255,.58)}html[data-theme=dark] .mini-card{background:rgba(255,255,255,.04)}
.source-card{margin:16px 0;padding:15px;border:1px solid var(--line);border-left:5px solid var(--teal);border-radius:8px;background:var(--soft)}.source-card.rosen-source{border-left-color:var(--indigo);background:#eef2ff}html[data-theme=dark] .source-card.rosen-source{background:#1f2547}.source-card__label{color:var(--indigo);font-size:12px;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.source-card__title{margin:4px 0 6px;color:var(--teal)}.source-delta{margin-top:10px;padding:10px 12px;border-left:4px solid var(--indigo);background:rgba(255,255,255,.62);border-radius:6px}.reference-image{margin:12px auto 0;padding:10px;width:fit-content;max-width:100%;border:1px solid var(--line);border-radius:7px;background:#fff}.reference-image img{display:block;max-width:100%;max-height:720px;object-fit:contain;cursor:zoom-in}.reference-image figcaption{margin-top:8px;color:#64748b;font-size:13px;font-style:italic;text-align:center}
.table-wrap{overflow-x:auto;margin:14px 0;border:1px solid var(--line);border-radius:8px}table{border-collapse:collapse;width:100%;background:var(--paper)}th,td{border-bottom:1px solid var(--line);padding:9px 11px;vertical-align:top;text-align:left}th{background:var(--teal);color:#fff}.mcq-wrapper{padding:16px;border:1px solid var(--line);border-radius:8px;background:var(--paper);margin:12px 0}.mcq-stem{font-weight:750}.mcq-options{display:grid;gap:8px;margin-top:10px}.mcq-opt{width:100%;padding:10px 12px;border:1px solid var(--line);border-radius:7px;background:#fff;color:#111827;text-align:left;cursor:pointer;font:inherit}.mcq-opt.is-correct{border-color:#059669;background:#dcfce7;color:#052e16}.mcq-opt.is-wrong{border-color:#dc2626;background:#fee2e2;color:#450a0a}.mcq-result{margin-top:10px;padding:10px 12px;border-radius:7px;font-weight:850}.mcq-result.is-correct{background:#dcfce7;color:#052e16}.mcq-result.is-wrong{background:#fee2e2;color:#450a0a}.opt-explain[hidden],.mcq-result[hidden]{display:none!important}.opt-explain{margin:8px 0;padding:9px;border-radius:6px;display:block}.opt-explain span{display:block}.opt-explain.is-correct{background:#dcfce7;color:#052e16}.opt-explain.is-wrong{background:#fee2e2;color:#450a0a}.score-pill{position:fixed;right:18px;bottom:18px;z-index:55;padding:10px 14px;border-radius:999px;color:#fff;background:linear-gradient(90deg,#0f766e,#4338ca);font-weight:850;box-shadow:var(--shadow);font-size:13px}
.image-modal{position:fixed;inset:0;display:none;place-items:center;z-index:80;padding:28px;background:rgba(0,0,0,.75)}.image-modal.is-open{display:grid}.image-modal img{max-width:96vw;max-height:92vh;background:white;border-radius:8px}.image-modal button{position:fixed;right:18px;top:18px}
@media(max-width:860px){#sidebar.sidebar{transform:translateX(-100%);transition:transform .2s}body.sidebar-open #sidebar.sidebar{transform:translateX(0)}#main.main{margin-left:0;padding-left:16px;padding-right:16px}.hero__title{font-size:28px}}
"""


SCRIPT = r"""
(function(){
 const root=document.documentElement,body=document.body,theme=document.querySelector('[data-theme-toggle]');
 function setTheme(t){root.setAttribute('data-theme',t); if(theme)theme.textContent=t==='dark'?'Light':'Dark';}
 try{setTheme(localStorage.getItem('chapter-theme')||'light')}catch(e){setTheme('light')}
 if(theme)theme.addEventListener('click',()=>{const n=root.getAttribute('data-theme')==='dark'?'light':'dark';try{localStorage.setItem('chapter-theme',n)}catch(e){}setTheme(n);});
 const tog=document.querySelector('[data-sidebar-toggle]'), close=document.querySelector('[data-sidebar-close]');
 if(tog)tog.addEventListener('click',()=>body.classList.toggle('sidebar-open'));
 if(close)close.addEventListener('click',()=>body.classList.remove('sidebar-open'));
 const links=[...document.querySelectorAll('.sidebar__link')], secs=[...document.querySelectorAll('.section[id]')];
 if('IntersectionObserver'in window){const obs=new IntersectionObserver(es=>{es.forEach(en=>{if(!en.isIntersecting)return;links.forEach(a=>a.classList.toggle('is-active',a.getAttribute('href')==='#'+en.target.id));})},{rootMargin:'-25% 0px -65% 0px',threshold:.1});secs.forEach(s=>obs.observe(s));}
 const modal=document.querySelector('[data-image-modal]'), modalImg=modal?modal.querySelector('img'):null;
 document.querySelectorAll('.reference-image img').forEach(img=>img.addEventListener('click',()=>{if(!modal||!modalImg)return;modalImg.src=img.src;modal.classList.add('is-open');}));
 if(modal)modal.addEventListener('click',e=>{if(e.target===modal||e.target.matches('[data-modal-close]'))modal.classList.remove('is-open');});
 const score=document.querySelector('[data-score-text]');
 function update(){const qs=[...document.querySelectorAll('.mcq-wrapper')], ans=qs.filter(q=>q.dataset.answered==='true'), cor=ans.filter(q=>q.dataset.correct==='true'); if(score)score.textContent=`${cor.length} correct / ${ans.length} answered / ${qs.length} total`;}
 document.querySelectorAll('.mcq-wrapper').forEach(q=>q.querySelectorAll('.mcq-opt').forEach(btn=>btn.addEventListener('click',()=>{if(q.dataset.answered==='true')return; const chosen=btn.dataset.optionKey, answer=q.dataset.answer, ok=chosen===answer; q.dataset.answered='true'; q.dataset.correct=ok?'true':'false'; q.querySelectorAll('.mcq-opt').forEach(b=>{const k=b.dataset.optionKey; if(k===answer)b.classList.add('is-correct'); else if(k===chosen)b.classList.add('is-wrong'); b.disabled=true;}); q.querySelectorAll('.opt-explain').forEach(x=>x.hidden=false); const r=q.querySelector('.mcq-result'); if(r){r.hidden=false;r.classList.add(ok?'is-correct':'is-wrong');r.textContent=ok?'Correct.':'Incorrect. Correct answer: '+answer;} update();})));
 update();
})();
"""


def main() -> None:
    source = CHAPTER.read_text(encoding="utf-8")
    backup = CHAPTER.with_suffix(CHAPTER.suffix + ".bak_rebuild_20260508")
    if not backup.exists():
        backup.write_bytes(CHAPTER.read_bytes())
    figures = extract_figures(source)
    for index in (1, 3, 4, 6, 7, 9, 10, 12, 13, 14, 15):
        if index not in figures:
            raise RuntimeError(f"Missing source figure {index}")

    html_doc = f"""<!doctype html>
<html lang="en" data-theme="light">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Chapter 178 - Atypical and Serotonergic Antidepressants</title>
<style>{STYLE}</style>
</head>
<body>
<header id="top-header"><button class="hdr-btn" data-sidebar-toggle title="Contents">☰</button><div class="hdr-title">Ch.178 Atypical and Serotonergic Antidepressants</div><button class="hdr-btn theme-btn" data-theme-toggle>Dark</button></header>
<div class="app">
<aside id="sidebar" class="sidebar"><button class="hdr-btn sidebar-close" data-sidebar-close>Close</button><div class="sidebar__block"><div class="sidebar__kicker">Chapter</div><h2>Atypical & Serotonergic Antidepressants</h2><p class="meta"><b>Spine:</b> Tintinalli Ch.178</p><p class="meta"><b>Pattern:</b> Ch186/Ch201 rebuild</p></div><div class="sidebar__block"><div class="sidebar__kicker">Contents</div><a class="sidebar__link" href="#overview">Overview</a><a class="sidebar__link" href="#bupropion">Bupropion</a><a class="sidebar__link" href="#trazodone">Trazodone</a><a class="sidebar__link" href="#ssri">SSRIs</a><a class="sidebar__link" href="#snri">SNRIs</a><a class="sidebar__link" href="#serotonin">Serotonin Syndrome</a><a class="sidebar__link" href="#drug-doses">Drug Dose Reference</a><a class="sidebar__link" href="#key-points">Key Points</a><a class="sidebar__link" href="#assessment">Assessment</a></div></aside>
<main id="main" class="main"><div class="content-wrap"><div class="utility-bar">Rebuilt chapter • source tables topic-local • reveal-all MCQs • final crop QA</div>
<section class="hero section" id="overview"><div class="eyebrow">Toxicology Chapter 178</div><h1 class="hero__title">Atypical and Serotonergic Antidepressants</h1><p class="lede">This chapter is organized around the ED decisions that change care: <mark>delayed seizures with bupropion</mark>, trazodone hypotension/QT risk, SSRI/SNRI ECG and seizure risk, and recognition of <u>serotonin syndrome</u>.</p><div class="callout warn"><strong>Board frame:</strong> do not manage these drugs as one generic antidepressant overdose. The dangerous pattern depends on agent, formulation, coingestants, ECG, seizure history, neuromuscular exam, and temperature.</div>{source_card(figures, 1, "Tintinalli Table 178-1. Atypical antidepressants", "Use this table as the agent map before separating bupropion, mirtazapine, trazodone, vilazodone, and vortioxetine into their clinical risk patterns.")}{rosen_card("Rosen source check: antidepressant overdose risk sorting", "Rosen emphasizes early risk sorting by toxidrome, ECG, seizure risk, and coingestants rather than relying on drug class names alone.", "Tintinalli gives the chapter-by-agent structure; Rosen reinforces bedside sorting and warns that mixed serotonergic exposures can look different from isolated single-agent ingestions.")}</section>
<section class="section" id="bupropion"><h2>Bupropion</h2><p>Bupropion is the atypical antidepressant that most often turns a quiet-looking ingestion into a delayed seizure problem. It is structurally stimulant-like and lowers seizure threshold; large or extended-release ingestions can produce agitation, tremor, hallucinations, tachycardia, QRS/QT changes, shock, and recurrent seizures hours after arrival.</p><p><mark>Extended-release bupropion needs prolonged observation</mark> because symptoms can be delayed after an initially reassuring exam. ED care starts with airway readiness, IV access, cardiac monitoring, glucose/electrolytes, and aggressive <u>benzodiazepine</u> treatment for agitation or seizures. Sodium bicarbonate is reasonable when QRS widening suggests sodium-channel blockade physiology; magnesium treats torsades.</p>{source_card(figures, 3, "Tintinalli Table 178-2. Treatment of bupropion overdose", "Placed inside the bupropion section because this is the actual bupropion treatment flow, not a drug-dose appendix item.")}<div class="callout danger"><strong>Trap:</strong> one normal early ECG or a calm early exam does not clear a large sustained-release bupropion ingestion.</div>{rosen_card("Rosen source check: bupropion seizures", "Rosen similarly highlights bupropion as a seizure-heavy antidepressant overdose and stresses supportive seizure control and monitoring.", "Tintinalli provides the table-based treatment sequence; Rosen adds the practical ED reminder that recurrent seizures and cardiotoxicity drive disposition even when the initial presentation is deceptively mild.")}</section>
<section class="section" id="trazodone"><h2>Trazodone</h2><p>Trazodone overdose is usually a sedation and vascular-tone problem, but severe cases can cause coma, respiratory depression from coingestants, <mark>orthostatic or persistent hypotension</mark>, QT prolongation, torsades, and priapism. Its alpha-1 blockade explains why fluids may not be enough in large ingestions.</p><p>Treatment is supportive: airway protection when needed, fluids for hypotension, direct-acting vasopressors such as norepinephrine for refractory shock, ECG monitoring, magnesium for torsades, and observation until mental status and hemodynamics are stable. <u>Priapism</u> is a time-sensitive urologic complication and should not be buried under general overdose care.</p>{source_card(figures, 4, "Tintinalli Table 178-3. Treatment of trazodone overdose", "Treatment table belongs here because trazodone hypotension/QT management is topic-specific.")}</section>
<section class="section" id="ssri"><h2>SSRIs</h2><p>Most isolated SSRI ingestions are benign compared with older antidepressants, but the ED still has to screen for dose, formulation, coingestants, serotonin toxicity, and ECG risk. <u>Citalopram and escitalopram</u> are the board-relevant exceptions because they can cause QT prolongation and torsades at high doses.</p><p>Management is supportive care, observation, ECG monitoring when the agent or dose warrants it, benzodiazepines for agitation/seizures, sodium bicarbonate if a prolonged QRS appears, and magnesium for torsades. The treatment threshold rises quickly when the exam shows <mark>clonus, hyperreflexia, diaphoresis, agitation, or hyperthermia</mark>.</p>{source_card(figures, 6, "Tintinalli Table 178-4. Selective serotonin reuptake inhibitors", "Agent reference for SSRI maximum adult dose and half-life, placed before the SSRI treatment logic.")}{source_card(figures, 7, "Tintinalli Table 178-5. Treatment of SSRI overdose", "Placed directly inside SSRI management so the treatment table does not drift into Drug Dose Reference.")}</section>
<section class="section" id="snri"><h2>SNRIs</h2><p>SNRIs, especially venlafaxine and desvenlafaxine, behave less benignly than many isolated SSRI ingestions. In overdose they can produce nausea, agitation, diaphoresis, hypertension, tachycardia, seizures, QRS/QT abnormalities, and serotonin syndrome. Large venlafaxine ingestions can deteriorate after an initially stable period.</p><p>ED management parallels SSRI care but with a lower threshold for seizure and cardiovascular monitoring: benzodiazepines for agitation/seizures, IV fluids and vasopressors for shock, sodium bicarbonate for significant QRS widening, magnesium for torsades, and <u>prolonged observation</u> when extended-release ingestion or severe symptoms are present.</p>{source_card(figures, 9, "Tintinalli Table 178-6. Serotonin/norepinephrine reuptake inhibitors", "SNRI agent table placed before the overdose distinctions.")}{source_card(figures, 10, "Tintinalli Table 178-7. Treatment of SNRI overdose", "Treatment table placed with SNRI management because venlafaxine-like toxicity changes monitoring and disposition.")}</section>
<section class="section" id="serotonin"><h2>Serotonin Syndrome</h2><p>Serotonin syndrome is a clinical diagnosis caused by excess serotonergic activity. The high-yield pattern is <mark>clonus plus hyperreflexia</mark>, often with agitation, tremor, diaphoresis, diarrhea, tachycardia, hypertension, and hyperthermia after a serotonergic medication change, overdose, or interaction.</p><p>The distinction from neuroleptic malignant syndrome matters: serotonin syndrome is usually faster and hyperreflexic with clonus, while NMS is slower with lead-pipe rigidity and bradyreflexia. Severe serotonin syndrome is a muscle-activity emergency; antipyretics alone do not work because the heat is generated by rigidity and clonus.</p><p>Treatment starts with stopping serotonergic agents, supportive care, IV fluids, benzodiazepines, and active cooling. Moderate to severe cases may receive enteral <u>cyproheptadine</u>. Life-threatening hyperthermia requires aggressive sedation, intubation, neuromuscular paralysis, and ICU-level cooling and monitoring.</p>{source_card(figures, 12, "Tintinalli Table 178-8. Serotonergic drugs", "Medication map placed before serotonin syndrome recognition so interacting agents are visible.")}{source_card(figures, 13, "Tintinalli Table 178-9. Clinical features of serotonin syndrome", "Clinical feature table placed next to the diagnostic narrative.")}{source_card(figures, 14, "Tintinalli Table 178-10. Serotonin syndrome vs NMS vs anticholinergic toxicity", "Differential table placed where the reader distinguishes the major hyperthermic toxidromes.")}{source_card(figures, 15, "Tintinalli Table 178-11. Severity pattern of serotonin syndrome", "Severity table placed beside treatment escalation because severity controls disposition and ICU threshold.")}{rosen_card("Rosen source check: hyperthermic toxidrome distinction", "Rosen uses the same practical distinction: clonus/hyperreflexia pushes toward serotonin syndrome, while slower lead-pipe rigidity points toward NMS.", "Tintinalli provides the comparison table; Rosen reinforces the bedside neurologic exam as the deciding move, not a send-out laboratory test.")}</section>
<section class="section" id="drug-doses"><h2>Drug Dose Reference</h2><p>This section is only a quick recap after the topic-specific treatment sections above. It should never be the only place where treatment logic or treatment tables appear.</p><div class="table-wrap"><table><thead><tr><th>Problem</th><th>ED treatment anchor</th><th>Board caution</th></tr></thead><tbody><tr><td>Bupropion seizures/agitation</td><td>Benzodiazepines; airway readiness; ICU/telemetry for severe or extended-release ingestion</td><td>Delayed and recurrent seizures are the disposition trap.</td></tr><tr><td>QRS widening</td><td>Sodium bicarbonate bolus and reassessment</td><td>Use ECG response and hemodynamics, not drug name alone.</td></tr><tr><td>Torsades/QT risk</td><td>Magnesium sulfate, electrolyte correction, telemetry</td><td>Citalopram/escitalopram and trazodone matter here.</td></tr><tr><td>Refractory hypotension</td><td>Fluids then direct-acting vasopressor such as norepinephrine</td><td>Trazodone alpha blockade can require pressors.</td></tr><tr><td>Serotonin syndrome</td><td>Stop agents, benzodiazepines, cooling; cyproheptadine enterally for moderate/severe cases</td><td>Severe hyperthermia needs paralysis/intubation, not antipyretics alone.</td></tr></tbody></table></div></section>
<section class="section" id="key-points"><h2>Key Points</h2><div class="grid"><div class="mini-card"><strong>Bupropion</strong><p>Delayed seizures, QRS/QT changes, and shock define risk.</p></div><div class="mini-card"><strong>Trazodone</strong><p>Sedation plus hypotension and QT effects; think direct vasopressors when fluids fail.</p></div><div class="mini-card"><strong>SSRIs/SNRIs</strong><p>Most SSRIs are supportive-care cases, but citalopram/escitalopram and venlafaxine deserve ECG/seizure respect.</p></div><div class="mini-card"><strong>Serotonin syndrome</strong><p>Clonus and hyperreflexia are the diagnosis handles; severe cases are cooling and paralysis emergencies.</p></div></div></section>
<section class="question-set section" id="assessment"><h2>Inline Assessment MCQs</h2>{build_mcqs()}</section>
</div></main></div>
<div class="score-pill" data-score-text>0 correct / 0 answered / 26 total</div><div class="image-modal" data-image-modal><button class="hdr-btn" data-modal-close>Close</button><img alt="Zoomed source"></div>
<script>{SCRIPT}</script>
</body></html>"""
    CHAPTER.write_text(html_doc, encoding="utf-8")
    print("rebuilt", CHAPTER)
    for token in ["source-card__label", "reference-image", "mcq-wrapper", "data-answer=", "<mark", "<u>", "Rosen source check", "Rosen vs Tintinalli"]:
        print(token, html_doc.count(token))


if __name__ == "__main__":
    main()
